### ISSUE TITLE
Erro no require da lib cpf_utils

### ISSUE THREAD

**Issue by johnwmcarneiro** [jacksonpires/documentos_br#2]
Após instalar a gem, não é possível carregar CPF_UTILS.

```
Users/John/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- cpf_utils (LoadError)
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/documentos_br-1.0.2/lib/documentos_br.rb:2:in `<top (required)>'
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:86:in `require'
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:81:in `each'
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:81:in `block in require'
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:70:in `each'
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:70:in `require'
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/bundler-1.12.4/lib/bundler.rb:102:in `require'
    from /Users/John/Workspace/rails/adamsc/config/application.rb:7:in `<top (required)>'
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/spring-1.7.1/lib/spring/application.rb:82:in `require'
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/spring-1.7.1/lib/spring/application.rb:82:in `preload'
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/spring-1.7.1/lib/spring/application.rb:143:in `serve'
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
    from /Users/John/.rvm/gems/ruby-2.1.2/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
    from /Users/John/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/John/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'

```

**Comment by jacksonpires** [comment]
Opa! Já foi corrigido. Falta só publicar a nova versão, mas, vc pode instalar a gem cpf_utils por fora que o funcionamento fica normal. blz?

**Comment by johnwmcarneiro** [comment]
Blz valeu Jackson.
